version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config.example.json:/srv/config.json
    depends_on:
      - mongo
      - redis
  mongo:
    image: "mongo:latest"
  redis:
    image: "redis:latest"
